name: Deploy to digitalocean

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          EVENTS: ${{ secrets.EVENTS }}
          SOIL_ORDERS: ${{ secrets.SOIL_ORDERS }}
          SOIL_ITEMS: ${{ secrets.SOIL_ITEMS }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESSTOKEN }}